version: "3.6"

x-rest-service: &rest-service
  image: shisa/examples/rest
  depends_on:
    - "consul"
    - "jaeger"
  environment:
    CONSUL_HTTP_ADDR: consul:8500
    JAEGER_AGENT_HOST: jaeger

x-rpc-service: &rpc-service
  image: shisa/examples/rpc
  depends_on:
    - "consul"
    - "jaeger"
  environment:
    CONSUL_HTTP_ADDR: consul:8500
    JAEGER_AGENT_HOST: jaeger

x-idp-service: &idp-service
  image: shisa/examples/idp
  depends_on:
    - "consul"
    - "jaeger"
  environment:
    CONSUL_HTTP_ADDR: consul:8500
    JAEGER_AGENT_HOST: jaeger

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
  consul:
    container_name: consul
    image: consul:1.0.6
    ports:
      - 8500:8500
    command: agent -dev -log-level warn -client "0.0.0.0"
  gw:
    container_name: gw
    image: shisa/examples/gw
    depends_on:
      - "consul"
      - "jaeger"
    ports:
      - 9001:9001
      - 9002:9002
      - 9003:9003
    environment:
      CONSUL_HTTP_ADDR: consul:8500
      JAEGER_AGENT_HOST: jaeger
    command: ./gw --addr="gw:9001" --debugaddr="gw:9002" --healthcheckaddr="gw:9003"
  rest-1:
    container_name: rest-1
    command: ./rest --addr="rest-1:9001"
    <<: *rest-service
  rest-2:
    container_name: rest-2
    command: ./rest --addr="rest-2:9001"
    <<: *rest-service
  rest-3:
    container_name: rest-3
    command: ./rest --addr="rest-3:9001"
    <<: *rest-service
  rest-4:
    container_name: rest-4
    command: ./rest --addr="rest-4:9001"
    <<: *rest-service
  rpc-1:
    container_name: rpc-1
    command: ./rpc --addr="rpc-1:9001"
    <<: *rpc-service
  rpc-2:
    container_name: rpc-2
    command: ./rpc --addr="rpc-2:9001"
    <<: *rpc-service
  rpc-3:
    container_name: rpc-3
    command: ./rpc --addr="rpc-3:9001"
    <<: *rpc-service
  rpc-4:
    container_name: rpc-4
    command: ./rpc --addr="rpc-4:9001"
    <<: *rpc-service
  idp-1:
    container_name: idp-1
    command: ./idp --addr="idp-1:9001"
    <<: *idp-service
  idp-2:
    container_name: idp-2
    command: ./idp --addr="idp-2:9001"
    <<: *idp-service
  idp-3:
    container_name: idp-3
    command: ./idp --addr="idp-3:9001"
    <<: *idp-service
  idp-4:
    container_name: idp-4
    command: ./idp --addr="idp-4:9001"
    <<: *idp-service
